site_name: Matsuri & NekoRay
site_url: https://matsuridayo.github.io/
repo_url: https://github.com/MatsuriDayo/Matsuri
edit_uri: ""
repo_name: Matsuri
copyright: CC BY-SA 4.0
theme:
  name: material
  logo: https://avatars.githubusercontent.com/u/95122236?s=200&v=4
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
markdown_extensions:
  - pymdownx.magiclink
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - 首页: index.md
  - 下载: download.md
  - Matsuri-配置: m-configuration.md
  - Matsuri-分组: m-group.md
  - Matsuri-路由: m-route.md
  - Matsuri-插件: m-plugin.md
  - Matsuri-FAQ: m-faq.md
  - Nekoray-配置: n-configuration.md
  - Nekoray-FAQ: n-faq.md
